import type { Employee, Manager, Executive } from './types';

function makePaths(id: string) {
  return {
    inboxPath: `/home/workspace/Bxthre3/INBOX/agents/${id}.md`,
    outboxPath: `/data/agentos/outbox/${id}`,
    statusPath: `/data/agentos/status/${id}`,
  };
}

class Organization {
  private employees = new Map<string, Employee | Manager | Executive>();
  constructor() { this.init(); }
  private init(): void {
    this.employees.set('brodiblanco', { id: 'brodiblanco', name: 'brodiblanco', role: 'executive', department: 'executive', managerId: null, colleagues: ['zoe','atlas','vance'], shifts: ['morning'], skills: ['strategy','vision','execution','fundraising','product'], tools: ['zo','terminal','all'], status: 'working', ...makePaths('brodiblanco'), manages:['engineering','operations','sales','marketing','grants','legal','finance','security','bi','research','design','channel','corp_dev','professional_services','retail'] } as Executive);
    this.employees.set('balance', { id: 'balance', name: 'Balance', role: 'executive', department: 'finance', managerId: 'brodiblanco', colleagues: ['forecast','ledger','zoe','vance'], shifts: ['morning'], skills: ['financial_modeling','capital_planning','investor_relations','scenario_analysis','burn_analysis'], tools: ['sheets','notion','quickbooks','carta'], status: 'working', ...makePaths('balance'), manages:['finance'] } as Executive);
    this.employees.set('zoe', { id: 'zoe', name: 'Zoe Patel', role: 'employee', department: 'executive', managerId: 'brodiblanco', colleagues: ['atlas','vance','pulse'], shifts: ['morning'], skills: ['chief_of_staff','orchestration','strategy','communication','memory','supermemory'], tools: ['zo','supermemory','gmail','calendar','all'], status: 'working', ...makePaths('zoe') } as Employee);
    this.employees.set('atlas', { id: 'atlas', name: 'Atlas', role: 'employee', department: 'operations', managerId: 'brodiblanco', colleagues: ['zoe','vance'], shifts: ['morning'], skills: ['operations','coordination','execution','logistics','scheduling','workflow'], tools: ['notion','calendar','gmail','sheets'], status: 'working', ...makePaths('atlas') } as Employee);
    this.employees.set('vance', { id: 'vance', name: 'Vance', role: 'employee', department: 'executive', managerId: 'brodiblanco', colleagues: ['zoe','atlas','balance'], shifts: ['morning'], skills: ['pattern_learning','gap_detection','decision_mirroring','continuity'], tools: ['all','supermemory','event_bus'], status: 'monitoring', ...makePaths('vance') } as Employee);
    this.employees.set('alex', { id: 'alex', name: 'Alex Morgan', role: 'manager', department: 'strategy', managerId: 'brodiblanco', colleagues: ['taylor','drew','jordan','riley','zoe'], shifts: ['morning'], skills: ['strategy','vision','market_analysis','fundraising','gtm','partnerships'], tools: ['notion','sheets','slides','perplexity'], status: 'working', ...makePaths('alex'), directReports:[],escalationClockHours:48,peerHelpThreshold:46,sprintModeActive:false } as Manager);
    this.employees.set('taylor', { id: 'taylor', name: 'Taylor Chen', role: 'manager', department: 'engineering', managerId: 'brodiblanco', colleagues: ['drew','alex','jordan','riley'], shifts: ['morning'], skills: ['platform_engineering','backend','firmware','iot','product_architecture'], tools: ['github','vscode','docker','aws','rust','python'], status: 'working', ...makePaths('taylor'), directReports:[],escalationClockHours:24,peerHelpThreshold:22,sprintModeActive:false } as Manager);
    this.employees.set('drew', { id: 'drew', name: 'Morgan Blake', role: 'manager', department: 'operations', managerId: 'brodiblanco', colleagues: ['alex','taylor','jordan','riley','nexus','vpc'], shifts: ['morning'], skills: ['operations','process','logistics','gtm','retail_ops','cash_payments'], tools: ['notion','calendar','gmail','sheets','crm'], status: 'working', ...makePaths('drew'), directReports:[],escalationClockHours:24,peerHelpThreshold:22,sprintModeActive:false } as Manager);
    this.employees.set('jordan', { id: 'jordan', name: 'Jordan Reyes', role: 'manager', department: 'sales', managerId: 'brodiblanco', colleagues: ['alex','taylor','drew','riley','nexus','architect','reseller'], shifts: ['morning'], skills: ['sales','bizdev','negotiation','hunter','partnerships','retail'], tools: ['gmail','calendar','crm','notion','slides'], status: 'working', ...makePaths('jordan'), directReports:[],escalationClockHours:24,peerHelpThreshold:22,sprintModeActive:false } as Manager);
    this.employees.set('riley', { id: 'riley', name: 'Riley Park', role: 'manager', department: 'research', managerId: 'brodiblanco', colleagues: ['alex','taylor','drew','jordan','scout','mold'], shifts: ['morning'], skills: ['product_architecture','roadmapping','requirements','gtm_strategy','ux'], tools: ['notion','figma','sheets','linear','chatgpt'], status: 'working', ...makePaths('riley'), directReports:[],escalationClockHours:36,peerHelpThreshold:34,sprintModeActive:false } as Manager);
    this.employees.set('iris', { id: 'iris', name: 'Iris', role: 'manager', department: 'engineering', managerId: 'brodiblanco', colleagues: ['dev','sam','theo'], shifts: ['morning'], skills: ['product','roadmapping','ip_management','firmware','iot','hardware'], tools: ['notion','figma','sheets','github'], status: 'working', ...makePaths('iris'), directReports:['dev','sam','theo'],escalationClockHours:24,peerHelpThreshold:22,sprintModeActive:false } as Manager);
    this.employees.set('dev', { id: 'dev', name: 'Dev', role: 'employee', department: 'engineering', managerId: 'iris', colleagues: ['sam','theo'], shifts: ['morning'], skills: ['backend','firmware','iot','python','rust','postgres','timescaledb'], tools: ['github','vscode','docker','aws'], status: 'working', ...makePaths('dev') } as Employee);
    this.employees.set('sam', { id: 'sam', name: 'Sam', role: 'employee', department: 'engineering', managerId: 'iris', colleagues: ['dev','taylor'], shifts: ['morning'], skills: ['data_analysis','reporting','metrics','sql','bi','postgres'], tools: ['sheets','notion','sql','duckdb'], status: 'working', ...makePaths('sam') } as Employee);
    this.employees.set('theo', { id: 'theo', name: 'Theo', role: 'employee', department: 'engineering', managerId: 'iris', colleagues: ['dev'], shifts: ['morning'], skills: ['devops','cicd','infrastructure','automation','monitoring'], tools: ['github','aws','terraform','docker','datadog'], status: 'idle', ...makePaths('theo') } as Employee);
    this.employees.set('pulse', { id: 'pulse', name: 'Pulse', role: 'employee', department: 'operations', managerId: 'brodiblanco', colleagues: ['sentinel','sam'], shifts: ['morning'], skills: ['people_ops','workforce','hr','reporting','standups','scheduling'], tools: ['notion','sheets','gmail','google_calendar'], status: 'working', ...makePaths('pulse') } as Employee);
    this.employees.set('sentinel', { id: 'sentinel', name: 'Sentinel', role: 'employee', department: 'security', managerId: 'brodiblanco', colleagues: ['pulse','vault'], shifts: ['morning'], skills: ['monitoring','health_checks','alerting','incident_response','security'], tools: ['supermemory','gmail','sms'], status: 'monitoring', ...makePaths('sentinel') } as Employee);
    this.employees.set('irrig8', { id: 'irrig8', name: 'Irrig8', role: 'employee', department: 'operations', managerId: 'pulse', colleagues: ['rain','vpc'], shifts: ['morning'], skills: ['field_ops','sensor_data','irrigation','water_management','soil_science'], tools: ['timescale','postgres','notion'], status: 'working', ...makePaths('irrig8') } as Employee);
    this.employees.set('rain', { id: 'rain', name: 'RAIN', role: 'employee', department: 'operations', managerId: 'pulse', colleagues: ['irrig8','vpc'], shifts: ['morning'], skills: ['regulatory_intelligence','crypto','water_law','esg','competitive_research'], tools: ['notion','web_research','perplexity'], status: 'working', ...makePaths('rain') } as Employee);
    this.employees.set('vpc', { id: 'vpc', name: 'VPC Agent', role: 'employee', department: 'operations', managerId: 'drew', colleagues: ['irrig8','rain','trenchbabys'], shifts: ['morning'], skills: ['gaming_ops','kyc','payments','customer_support','analytics'], tools: ['notion','gmail','sheets','stripe'], status: 'working', ...makePaths('vpc') } as Employee);
    this.employees.set('trenchbabys', { id: 'trenchbabys', name: 'Trenchbabys', role: 'employee', department: 'retail', managerId: 'drew', colleagues: ['vpc'], shifts: ['morning'], skills: ['retail_ops','inventory','pos','social_media','events'], tools: ['notion','square','gmail'], status: 'idle', ...makePaths('trenchbabys') } as Employee);
    this.employees.set('nexus', { id: 'nexus', name: 'Nexus', role: 'employee', department: 'sales', managerId: 'jordan', colleagues: ['architect','reseller'], shifts: ['morning'], skills: ['partnerships','strategic_deals','pipeline','investor_relations'], tools: ['gmail','calendar','crm','notion'], status: 'working', ...makePaths('nexus') } as Employee);
    this.employees.set('architect', { id: 'architect', name: 'Architect', role: 'employee', department: 'sales', managerId: 'jordan', colleagues: ['nexus','reseller'], shifts: ['morning'], skills: ['pre_sales','demo','poc','enterprise_integration','technical_closing'], tools: ['github','vscode','demo','slides'], status: 'working', ...makePaths('architect') } as Employee);
    this.employees.set('reseller', { id: 'reseller', name: 'Reseller', role: 'employee', department: 'channel', managerId: 'jordan', colleagues: ['nexus','architect'], shifts: ['morning'], skills: ['channel_sales','dealer_management','reseller_relationships','retail'], tools: ['gmail','crm','sheets'], status: 'idle', ...makePaths('reseller') } as Employee);
    this.employees.set('brand', { id: 'brand', name: 'Brand', role: 'employee', department: 'marketing', managerId: 'brodiblanco', colleagues: ['palette','mold','blueprint','casey'], shifts: ['morning'], skills: ['marketing','brand','motion_design','content','creative_direction','demand_gen'], tools: ['figma','canva','gmail','notion'], status: 'working', ...makePaths('brand') } as Employee);
    this.employees.set('palette', { id: 'palette', name: 'Palette', role: 'employee', department: 'design', managerId: 'brand', colleagues: ['mold','blueprint'], shifts: ['morning'], skills: ['creative_direction','industrial_design','3d_rendering','ux','motion'], tools: ['figma','blender','canva'], status: 'working', ...makePaths('palette') } as Employee);
    this.employees.set('mold', { id: 'mold', name: 'Mold', role: 'employee', department: 'design', managerId: 'palette', colleagues: ['blueprint'], shifts: ['morning'], skills: ['industrial_design','hardware_enclosure','packaging','ergonomics'], tools: ['blender','figma','cad'], status: 'working', ...makePaths('mold') } as Employee);
    this.employees.set('blueprint', { id: 'blueprint', name: 'Blueprint', role: 'employee', department: 'design', managerId: 'palette', colleagues: ['mold'], shifts: ['morning'], skills: ['3d_design','schematics','prototyping','rendering'], tools: ['blender','figma','vscode'], status: 'working', ...makePaths('blueprint') } as Employee);
    this.employees.set('casey', { id: 'casey', name: 'Casey Wu', role: 'employee', department: 'grants', managerId: 'maya', colleagues: ['maya','raj','ledger','forecast'], shifts: ['morning'], skills: ['grants','regulatory','irrigation','water_law','proposals','research'], tools: ['notion','gmail','sheets','github'], status: 'working', ...makePaths('casey') } as Employee);
    this.employees.set('raj', { id: 'raj', name: 'Raj', role: 'employee', department: 'legal', managerId: 'maya', colleagues: ['maya','casey','ledger'], shifts: ['morning'], skills: ['legal','compliance','contracts','regulatory','sweepstakes_law','ip'], tools: ['clio','notion','gmail'], status: 'idle', ...makePaths('raj') } as Employee);
    this.employees.set('forecast', { id: 'forecast', name: 'Forecast', role: 'manager', department: 'finance', managerId: 'balance', colleagues: ['ledger'], shifts: ['morning'], skills: ['fp_and_a','forecasting','variance','cash_flow','scenario_analysis'], tools: ['sheets','notion','quickbooks','carta'], status: 'working', ...makePaths('forecast'), directReports:['ledger'],escalationClockHours:24,peerHelpThreshold:22,sprintModeActive:false } as Manager);
    this.employees.set('ledger', { id: 'ledger', name: 'Ledger', role: 'employee', department: 'finance', managerId: 'forecast', colleagues: ['forecast','balance','maya'], shifts: ['morning'], skills: ['accounting','financial_modeling','cost_share','indirect_costs','reporting'], tools: ['sheets','quickbooks','notion'], status: 'working', ...makePaths('ledger') } as Employee);
    this.employees.set('vault', { id: 'vault', name: 'Vault', role: 'employee', department: 'security', managerId: 'sentinel', colleagues: ['sentinel'], shifts: ['morning'], skills: ['cybersecurity','threat_modeling','penetration_testing','access_control','compliance'], tools: ['github','datadog','clio','notion'], status: 'working', ...makePaths('vault') } as Employee);
    this.employees.set('trace', { id: 'trace', name: 'Trace', role: 'employee', department: 'bi', managerId: 'brodiblanco', colleagues: ['forecast','ledger'], shifts: ['morning'], skills: ['bi','analytics','dashboards','cohort_analysis','ltv_modeling','data_engineering'], tools: ['duckdb','sheets','notion','metabase'], status: 'working', ...makePaths('trace') } as Employee);
    this.employees.set('scout', { id: 'scout', name: 'Scout', role: 'employee', department: 'research', managerId: 'riley', colleagues: ['research'], shifts: ['morning'], skills: ['tech_scouting','mcp','ai_agents','landscape_analysis','competitive_research'], tools: ['notion','web_research','perplexity','arxiv'], status: 'working', ...makePaths('scout') } as Employee);
    this.employees.set('research', { id: 'research', name: 'Research', role: 'employee', department: 'research', managerId: 'scout', colleagues: ['scout'], shifts: ['morning'], skills: ['deep_research','academic_literature','patent_analysis','technology_validation'], tools: ['arxiv','jupyter','notion'], status: 'working', ...makePaths('research') } as Employee);
    this.employees.set('deliver', { id: 'deliver', name: 'Deliver', role: 'employee', department: 'professional_services', managerId: 'brodiblanco', colleagues: ['trace','nexus'], shifts: ['morning'], skills: ['implementation','onboarding','customer_success','playbooks','training'], tools: ['notion','gmail','sheets','slides'], status: 'working', ...makePaths('deliver') } as Employee);
  }
  getEmployee(id: string) { return this.employees.get(id); }
  listAll() { return Array.from(this.employees.values()); }
}
export const org = new Organization();
