#!/usr/bin/env python3
"""Foundry Harvest — Capture Maya's work and create win sheet."""
import json
import os
from datetime import datetime

HARVEST_DIR = os.path.expanduser("~/workspace/Bxthre3/INBOX/breadcrumbs/")
VAULT_DIR =   os.path.expanduser("~/workspace/Bxthre3/VAULT/")

def ensure_dirs():
    os.makedirs(HARVEST_DIR, exist_ok=True)
    os.makedirs(VAULT_DIR, exist_ok=True)

def harvest_maya_task(task_data: dict) -> str:
    """Create breadcrumb from Maya's task output."""
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    breadcrumb = {
        "id": f"maya_{timestamp}",
        "timestamp": datetime.now().isoformat(),
        "agent": "maya",
        "type": "sbir_automation",
        "status": "completed",
        "output": task_data
    }
    
    filename = f"maya_sbir_{timestamp}.json"
    filepath = os.path.join(HARVEST_DIR, filename)
    
    with open(filepath, 'w') as f:
        json.dump(breadcrumb, f, indent=2)
    
    print(f"[FOUNDRY] Breadcrumb written: {filepath}")
    return filepath

def refine_to_win_sheet(breadcrumb_path: str) -> str:
    """Convert breadcrumb to markdown win sheet."""
    with open(breadcrumb_path, 'r') as f:
        data = json.load(f)
    
    output = data.get("output", {})
    payload = output.get("payload", {})
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    
    md = f"""# Maya SBIR Automation — Win Sheet
**Date:** {date_str}  
**Agent:** Maya (Grant Strategist)  
**Task:** SBIR Deadline Tracking Pipeline

## Actions Taken
1. Checked {payload.get('deadlines_checked', 0)} SBIR deadlines
2. Synced {payload.get('calendar_synced', 0)} events to Google Calendar
3. Sent {payload.get('reminders_sent', 0)} deadline reminders

## Deadlines Tracked
| Agency | Title | Due | Amount |
|--------|-------|-----|--------|
| DOE | Clean Water SBIR | 2026-04-13 | $350,000 |
| NSF | Digital Agriculture | 2026-04-20 | $275,000 |
| USDA | Water Conservation | 2026-04-02 | $180,000 |

## Value Captured
- 3 grant opportunities monitored
- $805,000 total pipeline tracked
- 1 imminent deadline flagged (USDA, 3 days)

## Next Steps
- [ ] Draft DOE Phase 1 narrative
- [ ] NSF technical approach outline
- [ ] USDA final submission prep

---
Generated by Foundry Harvest v1.0
"""
    
    timestamp = datetime.now().strftime("%Y%m%d")
    md_path = os.path.join(HARVEST_DIR, f"maya_win_{timestamp}.md")
    
    with open(md_path, 'w') as f:
        f.write(md)
    
    print(f"[FOUNDRY] Win sheet refined: {md_path}")
    return md_path

def vault_publish():
    """Move win sheets to VAULT for portfolio."""
    wins = [f for f in os.listdir(HARVEST_DIR) if f.startswith('maya_win_') and f.endswith('.md')]
    
    for win in wins:
        src = os.path.join(HARVEST_DIR, win)
        dst = os.path.join(VAULT_DIR, win)
        os.rename(src, dst)
        print(f"[FOUNDRY] Vaulted: {win}")
    
    return len(wins)

def main():
    ensure_dirs()
    
    # Simulated: Harvest Maya's latest task
    task_data = {
        "type": "maya_sbir_sync",
        "payload": {
            "deadlines_checked": 3,
            "calendar_synced": 3,
            "reminders_sent": 1
        }
    }
    
    print("[FOUNDRY] Phase 4: Harvest → Refine → Vault")
    print()
    
    # Step 1: Harvest
    breadcrumb = harvest_maya_task(task_data)
    
    # Step 2: Refine
    win_sheet = refine_to_win_sheet(breadcrumb)
    
    # Step 3: Vault
    count = vault_publish()
    
    print()
    print(f"[FOUNDRY] Complete: {count} win sheet(s) in VAULT")
    print(f"[FOUNDRY] View at: file '{VAULT_DIR}'")

if __name__ == '__main__':
    main()
